/* DO NOT EDIT. This file (and "version") is generated by generate_version.bat. */ 
#ifndef LIB_JSON_CONFIG_VERSION_H_ 
#define LIB_JSON_CONFIG_VERSION_H_ 
#define LIBJSON_CONFIG_VERSION_MAJOR           0  
#define LIBJSON_CONFIG_VERSION_MINOR           1  
#define LIBJSON_CONFIG_VERSION_REVISION        0  
#define LIBJSON_CONFIG_VERSION_BUILD           0  
#define LIBJSON_CONFIG_VERSION_STRING          "0.1.0.0"  
#define LIBJSON_CONFIG_VERSION_STRING_EX       "libjson_config version:0.1.0.0 build at 2016-08-16 16:53:14"  
#endif 
